### ISSUE TITLE
index.vue 555-556 行 报错

### ISSUE THREAD

**Issue by Cluno1** [KuAi9/lb-audio-v3#1]
你好，很感谢你能分享你的代码，我最近在做一个学习的项目恰好需要一个播放组件，很幸运看到了你的代码。同时运用的时候发现在 index.vue 的 555-556 行由于没有判断，如果我的 musicList 为空，这里就变成了指针异常，盼采纳

**Comment by KuAi9** [comment]
感谢你的反馈，我已经在最新的版本中修复了，现在 musicList 可以为空数组

**Comment by Cluno1** [comment]
thank you
