### ISSUE TITLE
支持多种歌词，比如ass

### ISSUE THREAD

**Issue by xzxzhixin** [KuAi9/lb-audio-v3#2]

**Comment by KuAi9** [comment]
播放器内部暂时没有支持 ASS 格式的打算，但我会在下个版本中提供一个将 ASS 转 LRC 的工具方法，开发者可以用该方法自行转换

**Comment by KuAi9** [comment]
在 1.1.1 版本中提供了 convertASSToLRC 方法，可以用于将 ASS 转换为 LRC，示例请看 README.MD
