### ISSUE TITLE
更新musicList发现一些异常

### ISSUE THREAD

**Issue by Cluno1** [KuAi9/lb-audio-v3#4]
https://github.com/user-attachments/assets/8ecf95b1-ca8a-4adf-a665-a1dfe5ed1d02

动态添加musicList之后发现该组件会卡住，然后切歌只会重新播放

**Comment by Cluno1** [comment]
哈哈哈，我把报错也贴给你，绝无恶意。sweet heart heart

![image](https://github.com/user-attachments/assets/7d8da32f-ed00-4068-9c81-6621471fc6d9)

**Comment by KuAi9** [comment]
我在新的版本中修复了动态修改歌曲列表导致的渲染错误，但此错误的报错信息与你提供的不一致，你先安装最新版本试试是否已经解决，我将持续关注

**Comment by Cluno1** [comment]
great！已经解决。不过我使用时在changeLrc函数里面的playState.lrcList取值时还是全部都需要 Optional chaining ?. ，不然取值会报错误

**Comment by KuAi9** [comment]
> great！已经解决。不过我使用时在changeLrc函数里面的playState.lrcList取值时还是全部都需要 Optional chaining ?. ，不然取值会报错误

我没有复现出该错误，初始化当 lrc 为空，会为 lrc 会填充上 `[00:00.00]暂无歌词`，因此 playState.lrcList 第一项应该永远会有值存在不需要 `?.`，我需要贴一份 在线 demo 地址 或者发一个 demo 到我的邮箱来尝试复现该 bug

**Comment by Cluno1** [comment]
该bug可能是我对你的代码做了些改动的原因，我再看看
